SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBCOPIASEGURANCA;
CREATE DATABASE DBCOPIASEGURANCA;
USE DBCOPIASEGURANCA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100)
	, DT_NASCIMENTO DATE
	, CPF CHAR(11)
	, CIDADE VARCHAR(100)
	, ESTADO CHAR(2)
);

CREATE TABLE CLIENTE_LOG (
	IDCLIENTELOG INT NOT NULL PRIMARY KEY AUTO_INCREMENT
    , DT_ACAO DATETIME
    , ACAO VARCHAR(15)
	, IDCLIENTE_ANTES INT 
    , IDCLIENTE_DEPOIS INT 
	, NOME_ANTES VARCHAR(100)
	, NOME_DEPOIS VARCHAR(100)
	, DT_NASCIMENTO_ANTES DATE
	, DT_NASCIMENTO_DEPOIS DATE
	, CPF_ANTES CHAR(11)
	, CPF_DEPOIS CHAR(11)
	, CIDADE_ANTES VARCHAR(100)
	, CIDADE_DEPOIS VARCHAR(100)
	, ESTADO_ANTES CHAR(2)
	, ESTADO_DEPOIS CHAR(2)
);

CREATE TABLE HISTORICO (
	IDHISTORICO INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    , DT_ACAO DATETIME
    , ACAO VARCHAR(15)
    , TABELA VARCHAR(100)
    -- VARIAÇÃO, COLOCAR AS CHAVES PRIMARIAS PARA FACILITAR PESQUISA
    , IDCLIENTE INT
);

CREATE TABLE HISTORICO_DETALHE (
	IDHISTORICO_DETALHE INT NOT NULL AUTO_INCREMENT PRIMARY KEY
    , IDHISTORICO INT NOT NULL
    , CAMPO VARCHAR(100)
    , VALOR_ANTES TEXT
    , VALOR_DEPOIS TEXT
    , DT_ACAO DATETIME
	, FOREIGN KEY (IDHISTORICO) REFERENCES HISTORICO (IDHISTORICO)
);

DELIMITER $$
CREATE TRIGGER TR_CLIENTE_INSERTLOG AFTER INSERT ON CLIENTE FOR EACH ROW

BEGIN 
	-- VARIÁVEL NECESSÁRIA PARA A SEGUNDA OPÇÃO
	DECLARE IDHIST INT;

	-- PRIMEIRA OPÇÃO
	INSERT INTO CLIENTE_LOG (DT_ACAO , ACAO, IDCLIENTE_DEPOIS , NOME_DEPOIS , DT_NASCIMENTO_DEPOIS , CPF_DEPOIS , CIDADE_DEPOIS , ESTADO_DEPOIS)
	VALUES (NOW(), 'INSERT', NEW.IDCLIENTE, NEW.NOME, NEW.DT_NASCIMENTO, NEW.CPF, NEW.CIDADE, NEW.ESTADO); 
    
    -- SEGUNDA OPÇÃO
    INSERT INTO HISTORICO (DT_ACAO, ACAO, TABELA, IDCLIENTE) 
    VALUES (NOW(), 'INSERT', 'CLIENTE', NEW.IDCLIENTE);
    
    -- INSERE NA VARIÁVEL O ÚLTIMO ID CRIADO, QUE NO CASO FOI O DESSE INSERT AQUI DE CIMA
    SET IDHIST = LAST_INSERT_ID();
    
    -- INSERINDO UMA NOVA LINHA NA TABELA DETALHES PRA CADA COLUNA DA TABELA ORIGINAL
    -- ESSAS LINHAS CONTÊM O ID DA TABELA HISTÓRICO, O NOME DO CAMPO QUE FOI MEXIDO E O VALOR ADICIONADO
    INSERT INTO HISTORICO_DETALHE(IDHISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (IDHIST, 'IDCLIENTE', NEW.IDCLIENTE);
	INSERT INTO HISTORICO_DETALHE(IDHISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (IDHIST, 'NOME', NEW.NOME);
	INSERT INTO HISTORICO_DETALHE(IDHISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (IDHIST, 'DT_NASCIMENTO', NEW.DT_NASCIMENTO);
	INSERT INTO HISTORICO_DETALHE(IDHISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (IDHIST, 'CPF', NEW.CPF);
	INSERT INTO HISTORICO_DETALHE(IDHISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (IDHIST, 'CIDADE', NEW.CIDADE);
	INSERT INTO HISTORICO_DETALHE(IDHISTORICO, CAMPO, VALOR_DEPOIS)
    VALUES (IDHIST, 'ESTADO', NEW.ESTADO);
END $$
DELIMITER ;

-- TESTE 
INSERT INTO CLIENTE (NOME) VALUES ('EDUARDO');
SELECT * FROM CLIENTE;
SELECT * FROM CLIENTE_LOG;
SELECT * FROM HISTORICO;
SELECT * FROM HISTORICO_DETALHE WHERE IDHISTORICO = 1;

